# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pulze' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'CocoaAsyncSocket'

  # Pods for pulze

  target 'pulzeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pulzeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
